patternTime: dd.MM.yy HH:mm

telegram:
  enable: true
  token: TOKEN_BOT_API
  id: -1002100000000
  theme: 52

messages:
  nonePlayer: ‚ùì –ù–µ–∏–∑–≤–µ—Å—Ç–Ω–æ
  noneTime: –ù–∞–≤—Å–µ–≥–¥–∞
  kick:
    - ü¶∂ <b>–ö–ò–ö</b>
    - <b> </b>
    - <b>–ù–∞—Ä—É—à–∏—Ç–µ–ª—å:</b> {player}
    - <b>–ù–∞–∫–∞–∑–∞–ª:</b> {exec_player}
    - <b>–î–∞—Ç–∞:</b> {time}
    - <b>–ü—Ä–∏—á–∏–Ω–∞:</b> {reason}
    - <b>–†–µ–∂–∏–º:</b> {servers}
  ban:
    - üö´ <b>–ë–ê–ù</b>
    - <b> </b>
    - <b>–ù–∞—Ä—É—à–∏—Ç–µ–ª—å:</b> {player}
    - <b>–ù–∞–∫–∞–∑–∞–ª:</b> {exec_player}
    - <b>–î–∞—Ç–∞:</b> {time}
    - <b>–î–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å:</b> {time_end}
    - <b>–ü—Ä–∏—á–∏–Ω–∞:</b> {reason}
    - <b>–†–µ–∂–∏–º:</b> {servers}
  mute:
    - üîá <b>–ú–£–¢</b>
    - <b> </b>
    - <b>–ù–∞—Ä—É—à–∏—Ç–µ–ª—å:</b> {player}
    - <b>–ù–∞–∫–∞–∑–∞–ª:</b> {exec_player}
    - <b>–î–∞—Ç–∞:</b> {time}
    - <b>–î–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å:</b> {time_end}
    - <b>–ü—Ä–∏—á–∏–Ω–∞:</b> {reason}
    - <b>–†–µ–∂–∏–º:</b> {servers}
  warn:
    - ‚ö†Ô∏è <b>–ü–†–ï–î–£–ü–†–ï–ñ–î–ï–ù–ò–ï</b>
    - <b> </b>
    - <b>–ù–∞—Ä—É—à–∏—Ç–µ–ª—å:</b> {player}
    - <b>–ù–∞–∫–∞–∑–∞–ª:</b> {exec_player}
    - <b>–î–∞—Ç–∞:</b> {time}
    - <b>–î–ª–∏—Ç–µ–ª—å–Ω–æ—Å—Ç—å:</b> {time_end}
    - <b>–ü—Ä–∏—á–∏–Ω–∞:</b> {reason}
    - <b>–†–µ–∂–∏–º:</b> {servers}
  unban:
    - ‚úÖ <b>–†–ê–ó–ë–ê–ù</b>
    - <b> </b>
    - <b>–ù–∞—Ä—É—à–∏—Ç–µ–ª—å:</b> {player}
    - <b>–ò—Å–ø–æ–ª–Ω–∏—Ç–µ–ª—å:</b> {exec_player}
    - <b>–î–∞—Ç–∞:</b> {time}
    - <b>–ü—Ä–∏—á–∏–Ω–∞:</b> {reason}
    - <b>–†–µ–∂–∏–º:</b> {servers}
  unmute:
    - üîä <b>–†–ê–ó–ú–£–¢</b>
    - <b> </b>
    - <b>–ù–∞—Ä—É—à–∏—Ç–µ–ª—å:</b> {player}
    - <b>–ò—Å–ø–æ–ª–Ω–∏—Ç–µ–ª—å:</b> {exec_player}
    - <b>–î–∞—Ç–∞:</b> {time}
    - <b>–ü—Ä–∏—á–∏–Ω–∞:</b> {reason}
    - <b>–†–µ–∂–∏–º:</b> {servers}
  unwarn:
    - ‚úÖ <b>–†–ê–ó–í–ê–†–ù</b>
    - <b> </b>
    - <b>–ù–∞—Ä—É—à–∏—Ç–µ–ª—å:</b> {player}
    - <b>–ò—Å–ø–æ–ª–Ω–∏—Ç–µ–ª—å:</b> {exec_player}
    - <b>–î–∞—Ç–∞:</b> {time}
    - <b>–ü—Ä–∏—á–∏–Ω–∞:</b> {reason}
    - <b>–†–µ–∂–∏–º:</b> {servers}
